core/urls.py
from django.urls import path
from core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index')
]

estoque/urls.py
from django.urls import path
from estoque import views as v

app_name='estoque'

urlpatterns = [
    path('',v.estoque_entrada_list, name='estoque_entrada_list'),
    path('<int:pk>/',v.estoque_entrada_detail, name='estoque_entrada_detail'),
    
]

produto/urls.py
from django.urls import path
from produto import views as v

app_name = 'produto'

urlpatterns = [
    path('', v.produto_list, name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('core.urls')),
    path('produto/', include('produto.urls')),
    path('estoque/', include('estoque.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from venv import create
from django.db import models

# Create your models here.
class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', 
        auto_now_add=True,
        auto_now=False,
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True,
    )
    class Meta:
        abstract = True

estoque/models.py
from random import choices
from statistics import quantiles
from django.db import models
from django.contrib.auth.models import User
from core.models import TimeStampedModel
from produto.models import Produto
from django.urls import reverse_lazy

# Create your models here.

MOVIMENTO =(
    ('e', 'entrada'),
    ('s', 'saida'),
)

class Estoque(TimeStampedModel):
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE)
    nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO)

    class Meta:
        ordering = ('-created',)

    def __str__(self) -> str:
        return '{} - {} - {}'.format(self.pk, self.nf, self.created.strftime('%d-%m-%Y'))

    def get_absolute_url(self):
        return reverse_lazy("estoque:estoque_entrada_detail", kwargs={"pk": self.pk})
    
    def nf_formatetd(self):
        return str(self.nf).zfill(4)

class EstoqueItens(models.Model):
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, related_name='estoques')
    produto=models.ForeignKey(Produto, on_delete=models.CASCADE)   
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveBigIntegerField()
    
    class Meta:
        ordering = ('pk',)

    def __str__(self) -> str:
        return '{} - {} - {}'.format(self.pk, self.estoque.pk, self.produto)

produto/models.py
from email.policy import default
from enum import unique
from unittest.util import _MAX_LENGTH
from django.db import models
from django.urls import reverse_lazy

# Create your models here.


class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque minimo',default=0)

    class Meta:
        ordering = ('produto',)

    def __str__(self) -> str:
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

projeto/core/models.py
from venv import create
from django.db import models

# Create your models here.
class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', 
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True,
    )
    class Meta:
        abstract = True

projeto/produto/models.py
from email.policy import default
from enum import unique
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.


class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque minimo',default=0)

    class Meta:
        ordering = ('produto')

    def __str__(self) -> str:
        return self.produto

produto/forms.py
from dataclasses import field
from django import forms
from django import forms
from .models import Produto

class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

estoque/views.py
from multiprocessing import context
from re import template
from django.shortcuts import render
from .models import Estoque

# Create your views here.
def estoque_entrada_list(request):
    template_name= 'estoque_entrada_list.html'
    objects = Estoque.objects.filter(movimento='e')
    context = {'object_list': objects}
    return render(request, template_name, context)

def estoque_entrada_detail(request,pk):
    template_name= 'estoque_entrada_detail.html'
    obj = Estoque.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)
    

produto/views.py
from re import template
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from .models import Produto
from .forms import ProdutoForm


# Create your views here.

def produto_list(request):
    template_name='produto_list.html'
    objects=Produto.objects.all()
    context={'object_list': objects}
    return render(request,template_name, context)

def produto_detail(request, pk):
    template_name='produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context={'object': obj}
    return render(request,template_name, context)

def produto_add(request):
    template_name='produto_form.html'
    return render(request, template_name)

class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm

class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm

core/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <!-- ICONES -->
    <script src="https://kit.fontawesome.com/83c1730359.js" crossorigin="anonymous"></script>

    <title>Estoque</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-7mQhpDl5nRA5nY9lr8F1st2NbIly/8WqhjTp+0oFxEA/QUuvlbF6M1KXezGBh3Nb" crossorigin="anonymous">

    {% block css %} 
    <style>
        .ok{
            color: green;
        }

        .no{
            color: red;
        }
    </style>
    {% endblock css %}
</head>
<body>
{% include "includes/nav.html" %}
<div class="container">
    {% block content %} {% endblock content %}
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
{% block js %}

{% endblock js %}
</html>

core/templates/includes/nav.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'core:index'%}">Tabacarria do Lorran</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=" {% url 'produto:produto_list' %}">Produtos</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Estoque
            </a>
            <ul class="dropdown-menu text-center">
              <li><a class="dropdown-item" href=" {% url 'estoque:estoque_entrada_list' %}">Entradas</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Saídas</a></li>
            </ul>
          </li>
        </ul>
            <!-- PODE INSERIR UM FORM-->
      </div>
    </div>
  </nav>

core/templates/index.html
{% extends "base.html" %}

{% block content%}
    <div>
        <div class="container">
            <h1>Bem-vindo</h1>
        </div>
    </div>
{%endblock content%}

estoque/templates/estoque_entrada_detail.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'estoque:estoque_entrada_list'%}">Voltar</a>

<h2>{{object}}</h2>

<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">NF</th>
                <td>{{object.nf_formated}}</td>
            </tr>
            <tr>
                <th class="text-right">Data</th>
                <td>{{object.created}}</td>
            </tr>
            <tr>
                <th class="text-right">Funcionario</th>
                <td>{{object.funcionario.first_name}}</td>
            </tr>
        </tbody>
    </table>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Saldo</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object.estoques.all %}
            <tr>
                <td>{{obj.produto}}</td>
                <td>{{obj.quantidade}}</td>
                <td>{{obj.saldo}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

estoque/templates/estoque_entrada_list.html
{% extends 'base.html' %}

{% block content %}

<h2 class="d-flex justify-content-between">Estoque Entradas
    <span class="pull-right">
        <a href="#">
            <button class="btn btn-primary"><span class="fa fa-plus"></span>Adicionar</button>
        </a>
    </span>
</h2>

{% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Item</th>
                <th>NF</th>
                <th>Data</th>
                <th>Funcionario</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{{object.get_absolute_url }}"> {{ object }}</a>
                    </td>
                    <td>
                        {{object.nf_formated}}
                    </td>
                    <td>
                        {{object.created}}
                    </td>
                    <td>
                        {{object.funcionario.first_name}}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
{% endif %}

{% endblock content %}

produto/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}

    <a class="right" href="{% url 'produto:produto_list' %}">Voltar</a>
    <h1 class="d-flex justify-content-between"> {{object}}
        <span>
            <a href="{% url 'produto:produto_edit' object.pk%}">
                <button type="button" class="btn btn-success">
                    <span class="fa fa-pencil"></span>Editar
                </button>
            </a>
        </span>
    </h1>
    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right">Importado</th>
                    <td>
                        {% if object.importado %}
                            <i class="fa fa-check-circle ok"></i>
                        {% else %}
                            <i class="fa fa-minus-circle no"></i>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th class="text-right">NCM</th>
                    <td>{{ object.ncm}}</td>
                </tr>
                <tr>
                    <th class="text-right">Preço</th>
                    <td>{{ object.preco}}</td>
                </tr>
                <tr>
                    <th class="text-right">Estoque</th>
                    <td>{{ object.estoque}}</td>
                </tr>
                <tr>
                    <th class="text-right">Estoque Minimo</th>
                    <td>{{ object.estoque_minimo}}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock content %}

produto/templates/produto_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields%}
        <div class="form-group {% if field.errors%} has-error {% endif %}">
            <label for="{{field.id_for_label}}">
                {% if field.field.required %}
                    <span class="required">{{ field.label }}</span>
                {% else %}
                    {{field.label}}
                {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <span class="text-muted">{{error}}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
{% endblock content %}

{% block js %}
<script>    
    document.getElementById("id_importado").classList.remove("form-control");
</script>
{% endblock js %}

produto/templates/produto_list.html
{% extends "base.html" %}

{% block content%} 
    <div class="page-header">
        <h2 class="d-flex justify-content-between">Lista de Produtos
            <span class="pull-right">
                <a href="{% url 'produto:produto_add' %}">
                    <button class="btn btn-primary"><span class="fa fa-plus"></span>Adicionar</button>
                </a>
            </span>
        </h2>

        {% if object_list %}

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Importado</th>
                        <th>NCM</th>
                        <th>Produto</th>
                        <th>Preço</th>
                        <th class="text-center">Estoque</th>
                        <th class="text-center">Estoque mínimo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>
                                {% if object.importado %}
                                    <i class="fa fa-check-circle ok"></i>
                                {% else %}
                                    <i class="fa fa-minus-circle no"></i>
                                {% endif %}
                            </td>
                            <td>{{ object.ncm }}</td>
                            <td>
                                <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
                            </td>
                            <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
                            <td class="text-center">{{ object.estoque }}</td>
                            <td class="text-center">{{ object.estoque_minimo }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="alert alert-warning">Sem items na lista</p>
        {% endif %}
    </div>
{% endblock content%}

produto/templates/produtos_detail.html
{% extends "base.html" %}

{% block content %}

    <a class="right" href="{% url 'produto:produtos_list' %}">Voltar</a>
    <h1 class="d-flex justify-content-between"> {{object}}
        <span>
            <a href="">
                <button type="button" class="btn btn-success">
                    <span class="fa fa-pencil"></span>Editar
                </button>
            </a>
        </span>
    </h1>
    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right">Importado</th>
                    <td>
                        {% if object.importado %}
                            <i class="fa fa-check-circle ok"></i>
                        {% else %}
                            <i class="fa fa-minus-circle no"></i>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th class="text-right">NCM</th>
                    <td>{{ object.ncm}}</td>
                </tr>
                <tr>
                    <th class="text-right">Preço</th>
                    <td>{{ object.preco}}</td>
                </tr>
                <tr>
                    <th class="text-right">Estoque</th>
                    <td>{{ object.estoque}}</td>
                </tr>
                <tr>
                    <th class="text-right">Estoque Minimo</th>
                    <td>{{ object.estoque_minimo}}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock content %}

produto/templates/produtos_list.html
{% extends "base.html" %}

{% block content%} 
    <div class="page-header">
        <h2>Lista de Produtos</h2>

        {% if object_list %}

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Importado</th>
                        <th>NCM</th>
                        <th>Produto</th>
                        <th>Preço</th>
                        <th class="text-center">Estoque</th>
                        <th class="text-center">Estoque mínimo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>
                                {% if object.importado %}
                                    <i class="fa fa-check-circle ok"></i>
                                {% else %}
                                    <i class="fa fa-minus-circle no"></i>
                                {% endif %}
                            </td>
                            <td>{{ object.ncm }}</td>
                            <td>
                                <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
                            </td>
                            <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
                            <td class="text-center">{{ object.estoque }}</td>
                            <td class="text-center">{{ object.estoque_minimo }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="alert alert-warning">Sem intens na lista</p>
        {% endif %}
    </div>
{% endblock content%}